### ISSUE TITLE
XPC connection invalid

### ISSUE THREAD

**Issue by joshuajnoble** [mhamilt/macos-ble-examples#3]
When I try to run the central code as is I get the following error:

`2022-01-29 10:21:32.669089-0800 ble_central[10762:1512281] [CoreBluetooth] XPC connection invalid`

I'm actually looking to debug BLE connections for a different application that I'm building and figure this is a good way to do a little more debugging. I'm on OSX 12.1 running from XCode 13.2.1

**Comment by mhamilt** [comment]
Seems to be down to the order of events and having the `CBCentralManager` declared as a property and giving the  `BlePrinter` class as the delegate

Will update with a better structure when I get the chance, but in the meantime the main programme structure should look like:

```objective-c
/*
 Scan and list found devices
 */
#import <Foundation/Foundation.h>
#import "BluetoothDevicePrinter.h"
//------------------------------------------------------------------------------
int main(int argc, const char * argv[])
{
    @autoreleasepool {
        dispatch_queue_t bleQueue;
        BluetoothDevicePrinter * blePrinter = [BluetoothDevicePrinter new];
        CBCentralManager * manager = [[CBCentralManager alloc] initWithDelegate:blePrinter
                                                                          queue:bleQueue];
        
        CFRunLoopRun();
    }
    return 0;
}
```

Had the error

```
API MISUSE: <private> can only accept this command while in the powered on state
```

Only _after_ I had updated to Xcode 15, but prior to that I was still on Xcode 10 so it was a bit of a leap.

Note also, you should receive a prompt to allow bluetooth access from Xcode when running with the debugger.
